version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project_managers.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - '8000'
